### ISSUE TITLE
Falsely commented

### ISSUE THREAD

**Issue by Gansgar** [cslarsen/mandelbrot-js#4]
https://github.com/cslarsen/mandelbrot-js/blob/08cb05b4faaba6beb3298b52b6b340e36c3ff526/mandelbrot.js#L90

Sorry. But the formula in this line is wrong. It should be `z_{n+1} = z_{n}^2 + c`

**Comment by cslarsen** [comment]
Thanks, you are right!

**Comment by cslarsen** [comment]
Fixed on master

**Comment by tyalie** [comment]
You're welcome
